server:
  port: 8443
  ssl:
    enabled: true
    keyStoreType: JKS
    key-alias: vdab
    key-store: C:/etc/ssl/certs/vdab.jks
    key-store-password: 3DHpdKDFVafErV7X

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: https://localhost:8443/eureka/
  server:
    enableSelfPreservation: true
  instance:
    # If there are two running on the same machine this the second one must have host name 127.0.0.1
    hostname: localhost

# Security
vdab.key-store-certificate: C:/etc/ssl/certs/vdab.jks
vdab.key-store-password: 3DHpdKDFVafErV7X
vdab.trust-store-certificate: C:/etc/ssl/certs/vdab.jks
vdab.trust-store-password: 3DHpdKDFVafErV7X