server:
  port: 8446
  ssl:
    enabled: true
    keyStoreType: JKS
    key-alias: selfsigned
    key-store: /etc/ssl/certs/belgiantrain.jks
    key-store-password: password

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: https://azure-dev-belgianrail.be:8446/eureka/
  server:
    enableSelfPreservation: false