server:
  port: 8446
  ssl:
    enabled: true
    keyStoreType: JKS
    key-alias: selfsigned
    key-store: /etc/ssl/certs/belgiantrain.jks
    key-store-password: password

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: https://azure-dev-belgianrail.be:8446/eureka/
  server:
    enableSelfPreservation: true
  instance:
    # If there are two running on the same machine this the second one must have host name 127.0.0.1
    hostname: localhost