server:
  port: 8446
  ssl:
    enabled: false
    keyStoreType: JKS
    key-alias: localhost
    key-store: /etc/ssl/certs/belgiantrain.jks
    key-store-password: password

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8446/eureka/
  server:
    enableSelfPreservation: false
  instance:
    hostname: localhost